line_numbers = true
# details_json_tree = true
# details_max_height = 24
# details_tab_width = 4
# case_mode = "insensitive"
# session_filters = true
# session_stdin = true

[theme]
name = "catppuccin"

# [levels]
# error = { fg = "#1e1e2e", bg = "#f38ba8" }

# [ui]
# border = { fg = "#585b70", bg = "#1e1e2e" }
# border_width = 1
# border_padding = 1

[[columns]]
source = "level"
width = 5
align = "center"
padding = 1
# border = "#585b70"
# border_width = 1
# border_padding = 1

[[columns]]
source = "timestamp"

[[columns]]
source = "message"

[[columns]]
source = "annotations.url"
