name = "dracula"

[colors]
background = "#282a36"
foreground = "#f8f8f2"
selection = { fg = "#f8f8f2", bg = "#44475a" }
overlay = { fg = "#f8f8f2", bg = "#21222c" }
status = { fg = "#6272a4", bg = "#191a21" }
border = "#6272a4"
window_focus_border = "#f1fa8c"
search_match = { fg = "#282a36", bg = "#f1fa8c" }
dim = "#6272a4"

[levels]
trace = "#6272a4"
debug = "#8be9fd"
info = "#50fa7b"
warn = "#f1fa8c"
error = "#ff5555"
fatal = "#bd93f9"
unknown = "#f8f8f2"

[ui]
timestamp = "#8be9fd"
key = "#ff79c6"
string = "#50fa7b"
number = "#bd93f9"
bool = "#ffb86c"
null = "#6272a4"
border_color = { fg = "#6272a4", bg = "#282a36" }
border_width = 1
border_padding = 1
