name = "gotham"

[colors]
background = "#0c1014"
foreground = "#99d1ce"
selection = { fg = "#d3ebe9", bg = "#091f2e" }
overlay = { fg = "#99d1ce", bg = "#11151c" }
status = { fg = "#599cab", bg = "#0a0f14" }
border = "#245361"
window_focus_border = "#edb443"
search_match = { fg = "#0c1014", bg = "#edb443" }
dim = "#245361"

[levels]
trace = "#245361"
debug = "#599cab"
info = "#2aa889"
warn = "#edb443"
error = "#c23127"
fatal = "#888ca6"
unknown = "#99d1ce"

[ui]
timestamp = "#599cab"
key = "#599cab"
string = "#2aa889"
number = "#d26937"
bool = "#888ca6"
null = "#245361"
border_color = { fg = "#245361", bg = "#0c1014" }
border_width = 1
border_padding = 1
