name = "night-owl"

[colors]
background = "#011627"
foreground = "#d6deeb"
selection_bg = "#1d3b53"
selection_fg = "#d6deeb"
overlay_bg = "#011221"
status_bg = "#011221"
status_fg = "#a1aebf"
border = "#5f7e97"
window_focus_border = "#ecc48d"
search_match = { fg = "#011627", bg = "#ecc48d" }
dim = "#637777"

[levels]
trace = "#637777"
debug = "#82aaff"
info = "#addb67"
warn = "#ecc48d"
error = "#ef5350"
fatal = "#c792ea"
unknown = "#d6deeb"

[ui]
timestamp = "#82aaff"
key = "#7fdbca"
string = "#ecc48d"
number = "#f78c6c"
bool = "#c792ea"
null = "#637777"
# column_border = { fg = "#5f7e97", bg = "#011627" }
# column_border_width = 1
# column_border_padding = 1
# column_border_padding = { left = 1, right = 2 }
