name = "nord"

[colors]
background = "#2e3440"
foreground = "#eceff4"
selection_bg = "#434c5e"
selection_fg = "#eceff4"
overlay_bg = "#3b4252"
status_bg = "#232831"
status_fg = "#d8dee9"
border = "#4c566a"
search_match = "#ebcb8b"
dim = "#4c566a"

[levels]
trace = "#4c566a"
debug = "#81a1c1"
info = "#a3be8c"
warn = "#ebcb8b"
error = "#bf616a"
fatal = "#b48ead"
unknown = "#eceff4"

[ui]
timestamp = "#88c0d0"
key = "#8fbcbb"
string = "#a3be8c"
number = "#d08770"
bool = "#b48ead"
null = "#4c566a"
# column_border = { fg = "#4c566a", bg = "#2e3440" }
# column_border_width = 1
# column_border_padding = 1
# column_border_padding = { left = 1, right = 2 }
