name = "one-dark"

[colors]
background = "#282c34"
foreground = "#abb2bf"
selection_bg = "#3e4452"
selection_fg = "#abb2bf"
overlay_bg = "#21252b"
status_bg = "#21252b"
status_fg = "#9da5b4"
border = "#4b5263"
window_focus_border = "#e5c07b"
search_match = { fg = "#282c34", bg = "#e5c07b" }
dim = "#5c6370"

[levels]
trace = "#5c6370"
debug = "#61afef"
info = "#98c379"
warn = "#e5c07b"
error = "#e06c75"
fatal = "#c678dd"
unknown = "#abb2bf"

[ui]
timestamp = "#61afef"
key = "#56b6c2"
string = "#98c379"
number = "#d19a66"
bool = "#c678dd"
null = "#5c6370"
# column_border = { fg = "#4b5263", bg = "#282c34" }
# column_border_width = 1
# column_border_padding = 1
# column_border_padding = { left = 1, right = 2 }
