name = "rose-pine"

[colors]
background = "#191724"
foreground = "#e0def4"
selection_bg = "#403d52"
selection_fg = "#e0def4"
overlay_bg = "#1f1d2e"
status_bg = "#1f1d2e"
status_fg = "#908caa"
border = "#524f67"
window_focus_border = "#f6c177"
search_match = { fg = "#191724", bg = "#f6c177" }
dim = "#6e6a86"

[levels]
trace = "#6e6a86"
debug = "#9ccfd8"
info = "#31748f"
warn = "#f6c177"
error = "#eb6f92"
fatal = "#c4a7e7"
unknown = "#e0def4"

[ui]
timestamp = "#9ccfd8"
key = "#ebbcba"
string = "#31748f"
number = "#f6c177"
bool = "#c4a7e7"
null = "#6e6a86"
# column_border = { fg = "#524f67", bg = "#191724" }
# column_border_width = 1
# column_border_padding = 1
# column_border_padding = { left = 1, right = 2 }
