name = "solarized-light"

[colors]
background = "#fdf6e3"
foreground = "#657b83"
selection_bg = "#eee8d5"
selection_fg = "#586e75"
overlay_bg = "#eee8d5"
status_bg = "#eee8d5"
status_fg = "#93a1a1"
border = "#93a1a1"
window_focus_border = "#b58900"
search_match = { fg = "#fdf6e3", bg = "#b58900" }
dim = "#93a1a1"

[levels]
trace = "#93a1a1"
debug = "#268bd2"
info = "#859900"
warn = "#b58900"
error = "#dc322f"
fatal = "#6c71c4"
unknown = "#657b83"

[ui]
timestamp = "#268bd2"
key = "#2aa198"
string = "#859900"
number = "#cb4b16"
bool = "#6c71c4"
null = "#93a1a1"
border_color = { fg = "#93a1a1", bg = "#fdf6e3" }
border_width = 1
border_padding = 1
