name = "synthwave"

[colors]
background = "#262335"
foreground = "#ffffff"
selection = { fg = "#ffffff", bg = "#463465" }
overlay = { fg = "#ffffff", bg = "#241b2f" }
status = { fg = "#b6b1b1", bg = "#241b2f" }
border = "#495495"
window_focus_border = "#fede5d"
search_match = { fg = "#262335", bg = "#fede5d" }
dim = "#848bbd"

[levels]
trace = "#848bbd"
debug = "#36f9f6"
info = "#72f1b8"
warn = "#fede5d"
error = "#fe4450"
fatal = "#ff7edb"
unknown = "#ffffff"

[ui]
timestamp = "#36f9f6"
key = "#ff7edb"
string = "#ff8b39"
number = "#f97e72"
bool = "#ff7edb"
null = "#848bbd"
border_color = { fg = "#495495", bg = "#262335" }
border_width = 1
border_padding = 1
