name = "tokyo-night"

[colors]
background = "#1a1b26"
foreground = "#c0caf5"
selection = { fg = "#c0caf5", bg = "#33467c" }
overlay = { fg = "#c0caf5", bg = "#16161e" }
status = { fg = "#a9b1d6", bg = "#16161e" }
border = "#3b4261"
window_focus_border = "#e0af68"
search_match = { fg = "#1a1b26", bg = "#e0af68" }
dim = "#565f89"

[levels]
trace = "#565f89"
debug = "#7aa2f7"
info = "#9ece6a"
warn = "#e0af68"
error = "#f7768e"
fatal = "#bb9af7"
unknown = "#c0caf5"

[ui]
timestamp = "#7aa2f7"
key = "#7dcfff"
string = "#9ece6a"
number = "#ff9e64"
bool = "#bb9af7"
null = "#565f89"
border_color = { fg = "#3b4261", bg = "#1a1b26" }
border_width = 1
border_padding = 1
